# Generated by Django 3.2.5 on 2021-08-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cell_count', models.IntegerField(default=0)),
                ('code_cell_count', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=6)),
                ('dataset', models.JSONField()),
                ('function', models.JSONField()),
                ('library', models.JSONField()),
            ],
        ),
    ]
